export const USER_GUIDE_SECTIONS = [
  { title: "Getting Started", content: "Sign up, create or join an organization, and complete onboarding. EstateLeadOS is workflow software — not legal advice." },
  { title: "Selecting Markets", content: "Choose states and counties enabled on your organization's market license. Unauthorized markets show a license warning. Contact SCS Nova or your organization admin to enable access." },
  { title: "Importing CSV Files", content: "CSV import is the fallback when automated connectors are unavailable or research-only. Map columns, review duplicates, and verify licensed markets before importing." },
  { title: "Understanding Lead Scores", content: "Estate and deal potential scores are system-generated estimates. They do not guarantee profit, spread, or closing outcomes." },
  { title: "Reviewing Lead Detail", content: "Lead Detail shows why a lead was flagged, source records, compliance panel, document packet, outreach history, and pipeline stage." },
  { title: "Using State Deal Kits", content: "State Deal Kits provide state-specific workflows, equipment checklists, document checklists, and compliance context. Confirm requirements with qualified professionals." },
  { title: "Completing Equipment Checklists", content: "Required equipment varies by state and deal type. Complete checklists before advancing high-risk pipeline stages." },
  { title: "Completing Document Checklists", content: "Required documents are tracked per lead. Missing documents may block assignment or closing stages." },
  { title: "Running Compliance Checks", content: "The Compliance Rules Engine evaluates state/county rules. Elevated risk requires acknowledgement. Restricted risk blocks workflow." },
  { title: "Logging Outreach", content: "Log respectful outreach in Outreach CRM. The Outreach Safety Guard blocks predatory language. Do Not Contact records disable outreach." },
  { title: "Using Deal Calculator", content: "Deal Calculator provides estimated offer ranges. Outputs are estimates — EstateLeadOS does not guarantee profit." },
  { title: "Managing Buyers", content: "Add buyers, import buyer CSV, and review match explanations. Buyer data is organization-owned and isolated." },
  { title: "Tracking Assignments", content: "Assignment Tracker monitors assignment sent, closing scheduled, and recorded fees. Blockers enforce document and compliance readiness." },
  { title: "Reading Reports", content: "Reports distinguish estimated values, actual recorded values, and demo sample data. Financial disclaimers apply to all estimates." },
  { title: "Understanding Disclaimers", content: "EstateLeadOS does not provide legal, tax, brokerage, financial, or investment advice. Confirm state and local requirements with qualified professionals." },
  { title: "Demo Mode vs Fresh Start", content: "Demo mode loads fictional sample data across all modules. Fresh-start mode begins empty with guided onboarding prompts." },
  { title: "Getting Support", content: "Create support tickets from Help, Lead Detail, Document Center, Compliance Center, or the Support page. Organization users see only their organization's tickets." },
] as const;

export const ADMIN_GUIDE_SECTIONS = [
  { title: "SCS Nova Admin Overview", content: "SCS Nova retains master platform control across users, organizations, licensing, templates, and system health." },
  { title: "Managing Organizations", content: "Create, edit, suspend, and archive organizations. Set seat limits, market access, and data isolation. Cross-organization data leakage is prohibited." },
  { title: "Managing Users", content: "Invite users, assign roles, suspend accounts, and prevent role escalation by normal users." },
  { title: "Managing Market Licenses", content: "Enable state/county/city/ZIP licenses per organization. Expired or suspended licenses disable market access." },
  { title: "Managing States", content: "Enable or disable state support. State rules flow to compliance engine and deal kits." },
  { title: "Managing Counties", content: "County-level controls affect data connectors and market search. Disabling a county removes user access." },
  { title: "Managing Data Sources", content: "Review source terms before enabling automated access. EstateLeadOS only supports approved sources — no illegal scraping." },
  { title: "Managing Compliance Rules", content: "Compliance rules are workflow controls, not legal advice. Changes are audit logged." },
  { title: "Managing Document Templates", content: "SCS Nova controls master template library. Organization templates may be allowed per organization settings." },
  { title: "Managing Outreach Templates", content: "Outreach templates include safety rules. Predatory language patterns are blocked." },
  { title: "Managing Buyer Rules", content: "Configure buyer matching criteria and outreach templates per organization or platform defaults." },
  { title: "Managing White Label", content: "Approve or reject white-label settings. SCS Nova master control and legal disclaimers cannot be removed." },
  { title: "Reviewing Audit Logs", content: "Audit logs are append-only. Filter by organization, user, severity, and compliance events." },
  { title: "Handling Support Tickets", content: "Assign, update status, and link tickets to leads, documents, states, and counties." },
  { title: "Reviewing System Health", content: "Monitor connector health, failed jobs, import errors, and authentication status." },
  { title: "Demo Mode Controls", content: "Demo mode is environment-controlled via NEXT_PUBLIC_DEMO_MODE. Demo data must not contaminate fresh-start accounts." },
  { title: "Fresh-Start Controls", content: "Fresh-start organizations begin with no demo records. Onboarding prompts guide initial setup." },
  { title: "Security Notes", content: "No live secrets in code. API keys stored hashed. Webhook signatures required in production. Organization data isolation enforced." },
] as const;

export const QA_CHECKLIST = [
  "New user signs up", "User creates organization", "User selects state/county",
  "App checks market license", "App checks state support", "App checks county support",
  "User imports CSV", "CSV maps columns", "CSV detects missing fields", "CSV detects duplicates",
  "App scores leads", "Lead appears in Lead Feed", "User filters Market Search", "User opens Lead Detail",
  "Lead Detail explains flag reason", "Lead Detail shows source records", "User reviews State Deal Kit",
  "User checks equipment list", "User checks document list", "Compliance Rules Engine runs",
  "Elevated risk requires acknowledgement", "Restricted risk blocks workflow", "User generates documents",
  "Missing variables flagged", "User uploads document", "Document packet updates", "User logs outreach",
  "Outreach Safety Guard blocks predatory language", "DNC disables outreach", "User schedules follow-up",
  "User moves lead through pipeline", "Risky stage blocked without acknowledgement", "Deal Calculator runs",
  "Deal Calculator shows estimates not guarantees", "User creates buyer", "User imports buyer CSV",
  "User matches buyer", "Match explains why", "Assignment Tracker opens", "Assignment Sent blocks missing docs",
  "Closing Scheduled blocks missing checklist", "User records actual fee", "App reports outcome",
  "Admin updates state rules",   "Admin updates county rules", "Admin updates document template",
  "Admin disables county", "User loses county access",
  "Support ticket created", "Audit log records actions", "Unauthorized admin blocked",
  "Cross-org data blocked", "Demo mode shows sample data", "Fresh-start shows no demo data",
  "Export respects permissions", "Archived records auditable", "Global disclaimer visible",
] as const;

export const CHANGELOG_ENTRIES = [
  { phase: 1, title: "SaaS Shell & Roles", status: "Completed" },
  { phase: 2, title: "Lead Discovery Engine", status: "Completed" },
  { phase: 3, title: "State Deal Kits & Compliance", status: "Completed" },
  { phase: 4, title: "Outreach CRM", status: "Completed" },
  { phase: 5, title: "Document Center & Templates", status: "Completed" },
  { phase: 6, title: "Deal Calculator, Buyer Network, Assignments", status: "Completed" },
  { phase: 7, title: "SCS Nova Admin Console & Licensing", status: "Completed" },
  { phase: 8, title: "Final Integration & Launch Readiness", status: "Completed" },
] as const;

export const ROADMAP_ITEMS = [
  "Live data provider integrations",
  "Advanced API",
  "E-signature integrations",
  "Title company integrations",
  "Team automations",
  "Expanded state review",
  "Advanced reporting",
  "Enterprise white-label",
  "Mobile companion app (placeholder)",
] as const;
