import type { OutreachTemplate } from "@/lib/types/crm";

const ts = "2025-10-01T00:00:00Z";

export const STARTER_OUTREACH_TEMPLATES: OutreachTemplate[] = [
  {
    id: "tpl-soft-inquiry",
    organizationId: null,
    templateName: "Soft Inquiry Letter",
    category: "soft_inquiry_letter",
    channel: "direct_mail",
    stateApplicability: ["*"],
    dealTypeApplicability: ["*"],
    tone: "soft",
    body: "Hello {{owner_name}}, I'm reaching out about the property at {{property_address}}. I wanted to ask whether selling the property as-is is something you would ever consider. No pressure either way. If it is not a good fit, I completely understand.",
    variables: ["owner_name", "property_address", "user_name", "business_phone"],
    requiredDisclaimerFlag: true,
    dncReminderFlag: true,
    consentReminderFlag: false,
    safetyStatus: "approved",
    reviewStatus: "approved",
    lastReviewedAt: ts,
    active: true,
  },
  {
    id: "tpl-voicemail",
    organizationId: null,
    templateName: "Voicemail Script",
    category: "voicemail_script",
    channel: "voicemail",
    stateApplicability: ["*"],
    dealTypeApplicability: ["*"],
    tone: "no_pressure",
    body: "Hi, this is {{user_name}}. I'm calling about the property at {{property_address}}. I wanted to see if selling it as-is is something you would ever consider. No pressure at all. You can reach me at {{business_phone}}. Thank you.",
    variables: ["user_name", "property_address", "business_phone"],
    requiredDisclaimerFlag: true,
    dncReminderFlag: true,
    consentReminderFlag: false,
    safetyStatus: "approved",
    reviewStatus: "approved",
    lastReviewedAt: ts,
    active: true,
  },
  {
    id: "tpl-email",
    organizationId: null,
    templateName: "Email Inquiry",
    category: "email_inquiry",
    channel: "email",
    stateApplicability: ["*"],
    dealTypeApplicability: ["*"],
    tone: "professional",
    body: "Hello {{owner_name}}, I hope you're doing well. I'm reaching out about {{property_address}} to ask whether an as-is sale is something you would ever consider. If not, no problem at all. Thank you for your time.",
    variables: ["owner_name", "property_address", "user_name", "business_email"],
    requiredDisclaimerFlag: true,
    dncReminderFlag: true,
    consentReminderFlag: true,
    safetyStatus: "approved",
    reviewStatus: "approved",
    lastReviewedAt: ts,
    active: true,
  },
  {
    id: "tpl-follow-up",
    organizationId: null,
    templateName: "Follow-Up Letter",
    category: "follow_up_letter",
    channel: "direct_mail",
    stateApplicability: ["*"],
    dealTypeApplicability: ["*"],
    tone: "follow_up",
    body: "Hello {{owner_name}}, I wanted to follow up on my previous note about {{property_address}}. If selling the property as-is is something you would ever like to discuss, I'd be happy to talk. If not, I completely understand.",
    variables: ["owner_name", "property_address", "follow_up_date"],
    requiredDisclaimerFlag: true,
    dncReminderFlag: true,
    consentReminderFlag: false,
    safetyStatus: "approved",
    reviewStatus: "approved",
    lastReviewedAt: ts,
    active: true,
  },
  {
    id: "tpl-not-interested",
    organizationId: null,
    templateName: "Not Interested Response",
    category: "not_interested_response",
    channel: "email",
    stateApplicability: ["*"],
    dealTypeApplicability: ["*"],
    tone: "compliance_safe",
    body: "Thank you for letting me know. I understand completely and will not follow up further unless you ask me to. I appreciate your time.",
    variables: ["owner_name"],
    requiredDisclaimerFlag: false,
    dncReminderFlag: false,
    consentReminderFlag: false,
    safetyStatus: "approved",
    reviewStatus: "approved",
    lastReviewedAt: ts,
    active: true,
  },
  {
    id: "tpl-dnc-confirm",
    organizationId: null,
    templateName: "Do Not Contact Confirmation",
    category: "do_not_contact_confirmation",
    channel: "email",
    stateApplicability: ["*"],
    dealTypeApplicability: ["*"],
    tone: "compliance_safe",
    body: "Thank you for letting me know. I will mark this contact as Do Not Contact and will not reach out again.",
    variables: ["owner_name"],
    requiredDisclaimerFlag: false,
    dncReminderFlag: false,
    consentReminderFlag: false,
    safetyStatus: "approved",
    reviewStatus: "approved",
    lastReviewedAt: ts,
    active: true,
  },
  {
    id: "tpl-offer",
    organizationId: null,
    templateName: "Offer Explanation",
    category: "offer_explanation",
    channel: "email",
    stateApplicability: ["*"],
    dealTypeApplicability: ["direct_purchase"],
    tone: "informational",
    body: "Based on the information available and the as-is condition assumptions, I can share a possible offer range for your review. There is no obligation to accept, and you are encouraged to review any agreement with a qualified professional before signing.",
    variables: ["owner_name", "property_address"],
    requiredDisclaimerFlag: true,
    dncReminderFlag: false,
    consentReminderFlag: false,
    safetyStatus: "approved",
    reviewStatus: "approved",
    lastReviewedAt: ts,
    active: true,
  },
  {
    id: "tpl-call",
    organizationId: null,
    templateName: "First Call Script",
    category: "first_call_script",
    channel: "call",
    stateApplicability: ["*"],
    dealTypeApplicability: ["*"],
    tone: "soft",
    body: "Hello {{owner_name}}, my name is {{user_name}}. I'm calling about the property at {{property_address}}. I wanted to see if selling it as-is is something you would ever consider. No pressure either way — I completely understand if now isn't the right time.",
    variables: ["owner_name", "user_name", "property_address", "business_phone"],
    requiredDisclaimerFlag: true,
    dncReminderFlag: true,
    consentReminderFlag: false,
    safetyStatus: "approved",
    reviewStatus: "approved",
    lastReviewedAt: ts,
    active: true,
  },
];

export const BLOCKED_PHRASES = [
  { phrase: "i know someone died", severity: "blocked", reason: "Grief-exploiting language", alternative: "I'm reaching out about the property at [address]" },
  { phrase: "you probably need to sell", severity: "blocked", reason: "Pressure language", alternative: "whether selling as-is is something you would ever consider" },
  { phrase: "before the bank takes it", severity: "blocked", reason: "Fear-based pressure", alternative: "if selling the property is something you'd consider" },
  { phrase: "act fast", severity: "blocked", reason: "False urgency", alternative: "no pressure either way" },
  { phrase: "last chance", severity: "blocked", reason: "Scarcity pressure", alternative: "whenever works for you" },
  { phrase: "you must sell", severity: "blocked", reason: "Coercive language", alternative: "if selling is something you'd consider" },
  { phrase: "guaranteed cash", severity: "blocked", reason: "Investment guarantee", alternative: "a possible offer range for your review" },
  { phrase: "guaranteed profit", severity: "blocked", reason: "Profit guarantee", alternative: "estimated range based on available information" },
  { phrase: "i legally handle probate", severity: "blocked", reason: "Legal authority claim", alternative: "review with a qualified professional" },
  { phrase: "i am selling your property", severity: "blocked", reason: "Misrepresents ownership", alternative: "whether an as-is sale is something you'd consider" },
];
