import { CRM_PIPELINE_STAGES, type CrmPipelineStage, type PipelineStageDefinition } from "@/lib/types/crm";

export const PIPELINE_STAGE_DEFINITIONS: Record<CrmPipelineStage, PipelineStageDefinition> = {
  new_lead: {
    id: "new_lead", name: "New Lead", order: 1,
    description: "Initial lead created from discovery or import",
    requiredActions: ["Review source records", "Verify property data"],
    suggestedNextStep: "Review source records and scoring explanation",
    blockers: [], documentsNeeded: ["Lead source record"],
    complianceChecks: ["Source permission status"],
    allowedPreviousStages: [], allowedNextStages: ["needs_research", "researching", "dead_lead", "do_not_contact"],
    completionCriteria: "Lead reviewed and assigned",
  },
  needs_research: {
    id: "needs_research", name: "Needs Research", order: 2,
    description: "Missing information requires research",
    requiredActions: ["Identify missing fields", "Verify owner/property"],
    suggestedNextStep: "Verify owner, property, and source data",
    blockers: ["Missing parcel ID", "Unknown owner"],
    documentsNeeded: ["Property research sheet"],
    complianceChecks: ["County support status"],
    allowedPreviousStages: ["new_lead"],
    allowedNextStages: ["researching", "contact_ready", "dead_lead"],
    completionCriteria: "Missing data identified and research plan set",
  },
  researching: {
    id: "researching", name: "Researching", order: 3,
    description: "User actively researching lead",
    requiredActions: ["Complete property research", "Verify ownership"],
    suggestedNextStep: "Complete missing fields and owner verification",
    blockers: [], documentsNeeded: ["Owner/heir verification checklist"],
    complianceChecks: ["Source documents attached"],
    allowedPreviousStages: ["needs_research", "new_lead"],
    allowedNextStages: ["contact_ready", "needs_research", "dead_lead"],
    completionCriteria: "Research substantially complete",
  },
  contact_ready: {
    id: "contact_ready", name: "Contact Ready", order: 4,
    description: "Source and contact review ready for respectful outreach",
    requiredActions: ["Review outreach caution", "DNC screening"],
    suggestedNextStep: "Review outreach cautions and choose respectful template",
    blockers: ["DNC not screened", "State outreach warning not reviewed"],
    documentsNeeded: [], complianceChecks: ["Outreach safety", "DNC reminder"],
    allowedPreviousStages: ["researching", "needs_research"],
    allowedNextStages: ["first_outreach_sent", "follow_up_needed", "do_not_contact"],
    completionCriteria: "Outreach prerequisites acknowledged",
  },
  first_outreach_sent: {
    id: "first_outreach_sent", name: "First Outreach Sent", order: 5,
    description: "First contact attempt logged",
    requiredActions: ["Log communication", "Schedule follow-up"],
    suggestedNextStep: "Schedule follow-up reminder",
    blockers: [], documentsNeeded: [],
    complianceChecks: ["Communication log active"],
    allowedPreviousStages: ["contact_ready"],
    allowedNextStages: ["follow_up_needed", "conversation_started", "do_not_contact", "dead_lead"],
    completionCriteria: "First outreach logged with outcome",
  },
  follow_up_needed: {
    id: "follow_up_needed", name: "Follow-Up Needed", order: 6,
    description: "Follow-up date due or pending",
    requiredActions: ["Complete follow-up", "Log outcome"],
    suggestedNextStep: "Complete follow-up contact attempt",
    blockers: [], documentsNeeded: [],
    complianceChecks: ["DNC status"],
    allowedPreviousStages: ["first_outreach_sent", "conversation_started"],
    allowedNextStages: ["conversation_started", "interested", "do_not_contact", "dead_lead"],
    completionCriteria: "Follow-up completed or rescheduled",
  },
  conversation_started: {
    id: "conversation_started", name: "Conversation Started", order: 7,
    description: "Contact made — conversation in progress",
    requiredActions: ["Log conversation outcome", "Update notes"],
    suggestedNextStep: "Log outcome and interest level",
    blockers: [], documentsNeeded: [],
    complianceChecks: ["Consent status"],
    allowedPreviousStages: ["first_outreach_sent", "follow_up_needed"],
    allowedNextStages: ["interested", "follow_up_needed", "do_not_contact", "dead_lead"],
    completionCriteria: "Conversation outcome documented",
  },
  interested: {
    id: "interested", name: "Interested", order: 8,
    description: "Seller or contact showed interest",
    requiredActions: ["Document interest", "Plan next step"],
    suggestedNextStep: "Schedule appointment or begin offer research",
    blockers: [], documentsNeeded: ["Seller intake form"],
    complianceChecks: ["Owner verification"],
    allowedPreviousStages: ["conversation_started", "follow_up_needed"],
    allowedNextStages: ["appointment_set", "offer_research", "do_not_contact"],
    completionCriteria: "Interest level confirmed in notes",
  },
  appointment_set: {
    id: "appointment_set", name: "Appointment Set", order: 9,
    description: "Appointment scheduled with contact",
    requiredActions: ["Confirm appointment", "Prepare property research"],
    suggestedNextStep: "Complete property research before appointment",
    blockers: [], documentsNeeded: ["Property research sheet"],
    complianceChecks: [], allowedPreviousStages: ["interested"],
    allowedNextStages: ["offer_research", "negotiating", "closed_lost"],
    completionCriteria: "Appointment completed or rescheduled",
  },
  offer_research: {
    id: "offer_research", name: "Offer Research", order: 10,
    description: "User preparing offer analysis",
    requiredActions: ["Run deal analysis", "Review comps"],
    suggestedNextStep: "Use Deal Calculator (Phase 6)",
    blockers: [], documentsNeeded: ["Comparable sales worksheet", "Repair estimate worksheet"],
    complianceChecks: [], allowedPreviousStages: ["interested", "appointment_set"],
    allowedNextStages: ["offer_sent", "negotiating"],
    completionCriteria: "Offer range determined",
  },
  offer_sent: {
    id: "offer_sent", name: "Offer Sent", order: 11,
    description: "Offer presented to seller",
    requiredActions: ["Log offer details", "Track response"],
    suggestedNextStep: "Log seller response in communication log",
    blockers: [], documentsNeeded: ["Purchase offer worksheet"],
    complianceChecks: [], allowedPreviousStages: ["offer_research", "negotiating"],
    allowedNextStages: ["negotiating", "under_contract", "closed_lost"],
    completionCriteria: "Offer response received",
  },
  negotiating: {
    id: "negotiating", name: "Negotiating", order: 12,
    description: "Terms being discussed",
    requiredActions: ["Update notes", "Track document requirements"],
    suggestedNextStep: "Update notes and required documents checklist",
    blockers: [], documentsNeeded: ["Deal memo"],
    complianceChecks: ["State deal kit reviewed"],
    allowedPreviousStages: ["offer_sent", "appointment_set"],
    allowedNextStages: ["under_contract", "closed_lost", "offer_sent"],
    completionCriteria: "Terms agreed or declined",
  },
  under_contract: {
    id: "under_contract", name: "Under Contract", order: 13,
    description: "Contract executed — compliance review required",
    requiredActions: ["Complete compliance checklist", "Attach source documents"],
    suggestedNextStep: "Run compliance review and document tracking",
    blockers: ["Phase 3 Under Contract blockers"],
    documentsNeeded: ["Purchase agreement checklist", "Compliance acknowledgement"],
    complianceChecks: ["Under Contract blockers cleared", "Owner verified"],
    allowedPreviousStages: ["negotiating", "offer_sent"],
    allowedNextStages: ["compliance_review", "closed_lost"],
    completionCriteria: "All Under Contract blockers resolved",
    requiresComplianceClearance: true,
  },
  compliance_review: {
    id: "compliance_review", name: "Compliance Review", order: 14,
    description: "Lead under compliance review",
    requiredActions: ["Resolve blockers", "Complete acknowledgements"],
    suggestedNextStep: "Resolve active workflow blockers",
    blockers: ["Active compliance blockers"],
    documentsNeeded: ["State risk acknowledgement"],
    complianceChecks: ["Compliance Rules Engine"],
    allowedPreviousStages: ["under_contract"],
    allowedNextStages: ["buyer_matching", "under_contract", "closed_lost"],
    completionCriteria: "Compliance review complete",
    requiresComplianceClearance: true,
  },
  buyer_matching: {
    id: "buyer_matching", name: "Buyer Matching", order: 15,
    description: "Matching buyer for disposition",
    requiredActions: ["Review buyer readiness"],
    suggestedNextStep: "Buyer Network tools (Phase 6)",
    blockers: ["Assignment readiness checks"],
    documentsNeeded: ["Buyer profile sheet"],
    complianceChecks: ["Buyer/assignee disclosure"],
    allowedPreviousStages: ["compliance_review", "under_contract"],
    allowedNextStages: ["assignment_sent", "closing_scheduled"],
    completionCriteria: "Buyer matched",
    requiresComplianceClearance: true,
  },
  assignment_sent: {
    id: "assignment_sent", name: "Assignment Sent", order: 16,
    description: "Assignment documents sent",
    requiredActions: ["Track assignment status"],
    suggestedNextStep: "Track signature and title company status",
    blockers: ["Phase 3 Assignment blockers"],
    documentsNeeded: ["Assignment agreement checklist"],
    complianceChecks: ["Assignment blockers cleared", "Brokerage interest acknowledgement"],
    allowedPreviousStages: ["buyer_matching"],
    allowedNextStages: ["closing_scheduled", "compliance_review"],
    completionCriteria: "Assignment signed",
    requiresComplianceClearance: true,
  },
  closing_scheduled: {
    id: "closing_scheduled", name: "Closing Scheduled", order: 17,
    description: "Closing date scheduled",
    requiredActions: ["Complete closing checklist"],
    suggestedNextStep: "Closing checklist (Phase 5)",
    blockers: ["Phase 3 Closing blockers"],
    documentsNeeded: ["Closing checklist", "Title company intake form"],
    complianceChecks: ["Closing blockers cleared"],
    allowedPreviousStages: ["assignment_sent", "buyer_matching", "under_contract"],
    allowedNextStages: ["closed_won", "closed_lost"],
    completionCriteria: "Closing completed",
    requiresComplianceClearance: true,
  },
  closed_won: {
    id: "closed_won", name: "Closed Won", order: 18,
    description: "Deal closed successfully",
    requiredActions: ["Record outcome", "Archive documents"],
    suggestedNextStep: "Record estimated/actual spread (Phase 6)",
    blockers: [], documentsNeeded: ["Communication log export"],
    complianceChecks: [], allowedPreviousStages: ["closing_scheduled"],
    allowedNextStages: [], completionCriteria: "Outcome recorded",
  },
  closed_lost: {
    id: "closed_lost", name: "Closed Lost", order: 19,
    description: "Deal lost — reason required",
    requiredActions: ["Record lost reason"],
    suggestedNextStep: "Archive or schedule future follow-up",
    blockers: [], documentsNeeded: [],
    complianceChecks: [], allowedPreviousStages: ["negotiating", "offer_sent", "under_contract", "closing_scheduled"],
    allowedNextStages: ["dead_lead", "follow_up_needed"],
    completionCriteria: "Lost reason documented",
  },
  dead_lead: {
    id: "dead_lead", name: "Dead Lead", order: 20,
    description: "Lead no longer viable",
    requiredActions: ["Record dead reason"],
    suggestedNextStep: "No further action unless reopened",
    blockers: [], documentsNeeded: [],
    complianceChecks: [], allowedPreviousStages: CRM_PIPELINE_STAGES.filter(s => s !== "dead_lead" && s !== "do_not_contact") as CrmPipelineStage[],
    allowedNextStages: ["needs_research"],
    completionCriteria: "Dead reason recorded",
  },
  do_not_contact: {
    id: "do_not_contact", name: "Do Not Contact", order: 21,
    description: "Contact requested no further outreach",
    requiredActions: ["Set DNC record", "Disable outreach"],
    suggestedNextStep: "Preserve audit trail — outreach disabled",
    blockers: [], documentsNeeded: [],
    complianceChecks: ["DNC recorded"],
    allowedPreviousStages: CRM_PIPELINE_STAGES.filter(s => s !== "do_not_contact") as CrmPipelineStage[],
    allowedNextStages: [],
    completionCriteria: "DNC reason recorded and outreach disabled",
  },
};

export const KANBAN_COLUMNS: CrmPipelineStage[] = [
  "new_lead", "needs_research", "contact_ready", "first_outreach_sent",
  "follow_up_needed", "interested", "offer_sent", "under_contract",
  "compliance_review", "buyer_matching", "assignment_sent", "closing_scheduled",
  "closed_won", "closed_lost",
];

export function getStageName(stage: CrmPipelineStage): string {
  return PIPELINE_STAGE_DEFINITIONS[stage]?.name ?? stage;
}
