export const SUBSCRIPTION_PLANS = [
  {
    id: "starter",
    name: "Starter",
    priceMonthly: 79,
    priceAnnual: 790,
    features: [
      "Limited states",
      "Limited leads",
      "Basic CRM",
      "Basic document checklist",
    ],
    limits: {
      states: 3,
      monthlyLeads: 100,
      seats: 1,
      dealCalculator: false,
      outreachTools: false,
      stateDealKits: false,
      buyerNetwork: false,
      assignmentTracker: false,
      auditTrail: false,
      advancedReporting: false,
      apiAccess: false,
      whiteLabel: false,
    },
  },
  {
    id: "pro",
    name: "Pro",
    priceMonthly: 199,
    priceAnnual: 1990,
    features: [
      "More states",
      "More leads",
      "Deal Calculator",
      "Outreach tools",
      "State Deal Kits",
    ],
    limits: {
      states: 15,
      monthlyLeads: 500,
      seats: 1,
      dealCalculator: true,
      outreachTools: true,
      stateDealKits: true,
      buyerNetwork: false,
      assignmentTracker: false,
      auditTrail: false,
      advancedReporting: false,
      apiAccess: false,
      whiteLabel: false,
    },
  },
  {
    id: "team",
    name: "Team",
    priceMonthly: 499,
    priceAnnual: 4990,
    features: [
      "Team seats",
      "Buyer Network",
      "Assignment Tracker",
      "Audit Trail",
      "Advanced reporting",
    ],
    limits: {
      states: 30,
      monthlyLeads: 2000,
      seats: 10,
      dealCalculator: true,
      outreachTools: true,
      stateDealKits: true,
      buyerNetwork: true,
      assignmentTracker: true,
      auditTrail: true,
      advancedReporting: true,
      apiAccess: false,
      whiteLabel: false,
    },
  },
  {
    id: "market_license",
    name: "Market License",
    priceMonthly: 999,
    priceAnnual: 9990,
    features: [
      "County/state-level licensing",
      "Larger lead volume",
      "Data automation",
      "Team workflow",
    ],
    limits: {
      states: 50,
      monthlyLeads: 10000,
      seats: 25,
      dealCalculator: true,
      outreachTools: true,
      stateDealKits: true,
      buyerNetwork: true,
      assignmentTracker: true,
      auditTrail: true,
      advancedReporting: true,
      apiAccess: false,
      whiteLabel: false,
    },
  },
  {
    id: "enterprise",
    name: "Enterprise",
    priceMonthly: null,
    priceAnnual: null,
    features: [
      "Custom access",
      "White-label options",
      "API access",
      "Dedicated support",
    ],
    limits: {
      states: 50,
      monthlyLeads: null,
      seats: null,
      dealCalculator: true,
      outreachTools: true,
      stateDealKits: true,
      buyerNetwork: true,
      assignmentTracker: true,
      auditTrail: true,
      advancedReporting: true,
      apiAccess: true,
      whiteLabel: true,
    },
  },
] as const;

export type PlanId = (typeof SUBSCRIPTION_PLANS)[number]["id"];
