import type {
  AccruedMoneyRecord,
  DealFinancials,
  ExpenseRecord,
} from "@/lib/types/analytics";

const ts = (daysAgo: number) =>
  new Date(Date.now() - daysAgo * 86400000).toISOString();

export const DEMO_DEAL_FINANCIALS: DealFinancials[] = [
  {
    id: "df-1",
    organizationId: "demo-org",
    leadId: "lead-demo-1",
    assignmentId: "asgn-1",
    estimatedArv: 290000,
    estimatedRepairs: 30000,
    investorMaxOffer: 149900,
    suggestedSellerOffer: 129900,
    targetAssignmentFee: 20000,
    minimumAcceptableSpread: 15000,
    estimatedSpread: 20000,
    agreedAssignmentFee: 18000,
    accruedAmount: 18000,
    pendingPayoutAmount: 18000,
    receivedAmount: null,
    expensesTotal: 2450,
    projectedNetProfit: 17550,
    actualNetProfit: null,
    financialStatus: "accrued",
    createdAt: ts(14),
    updatedAt: ts(2),
  },
  {
    id: "df-2",
    organizationId: "demo-org",
    leadId: "lead-demo-2",
    assignmentId: "asgn-2",
    estimatedArv: 195000,
    estimatedRepairs: 28000,
    investorMaxOffer: 91640,
    suggestedSellerOffer: 79640,
    targetAssignmentFee: 12000,
    minimumAcceptableSpread: 8000,
    estimatedSpread: 12000,
    agreedAssignmentFee: null,
    accruedAmount: null,
    pendingPayoutAmount: null,
    receivedAmount: null,
    expensesTotal: 890,
    projectedNetProfit: 11110,
    actualNetProfit: null,
    financialStatus: "projected",
    createdAt: ts(20),
    updatedAt: ts(5),
  },
  {
    id: "df-3",
    organizationId: "demo-org",
    leadId: "lead-demo-3",
    estimatedArv: 165000,
    estimatedRepairs: 22000,
    investorMaxOffer: 85000,
    suggestedSellerOffer: 72000,
    targetAssignmentFee: 10000,
    minimumAcceptableSpread: 7000,
    estimatedSpread: 10000,
    agreedAssignmentFee: 10000,
    accruedAmount: null,
    pendingPayoutAmount: null,
    receivedAmount: 10000,
    expensesTotal: 1200,
    projectedNetProfit: 8800,
    actualNetProfit: 8800,
    financialStatus: "received",
    createdAt: ts(45),
    updatedAt: ts(10),
  },
];

export const DEMO_EXPENSE_RECORDS: ExpenseRecord[] = [
  {
    id: "exp-1",
    organizationId: "demo-org",
    leadId: "lead-demo-1",
    category: "government_record_fees",
    vendor: "Harris County Clerk",
    amount: 45,
    expenseDate: ts(30).slice(0, 10),
    paymentStatus: "paid",
    notes: "Probate record pull",
    createdAt: ts(30),
    updatedAt: ts(30),
  },
  {
    id: "exp-2",
    organizationId: "demo-org",
    leadId: "lead-demo-1",
    category: "attorney_review_fees",
    vendor: "Demo Legal Review LLC",
    amount: 750,
    expenseDate: ts(12).slice(0, 10),
    paymentStatus: "planned",
    notes: "Attorney review — estimated",
    createdAt: ts(12),
    updatedAt: ts(12),
  },
  {
    id: "exp-3",
    organizationId: "demo-org",
    leadId: "lead-demo-2",
    category: "document_fees",
    vendor: "Duval County Records",
    amount: 35,
    expenseDate: ts(18).slice(0, 10),
    paymentStatus: "paid",
    createdAt: ts(18),
    updatedAt: ts(18),
  },
  {
    id: "exp-4",
    organizationId: "demo-org",
    category: "software_subscription",
    vendor: "EstateLeadOS / SCS Nova",
    amount: 299,
    expenseDate: ts(1).slice(0, 10),
    paymentStatus: "paid",
    notes: "Monthly platform subscription",
    createdAt: ts(1),
    updatedAt: ts(1),
  },
  {
    id: "exp-5",
    organizationId: "demo-org",
    leadId: "lead-demo-3",
    category: "title_company_fees",
    vendor: "Metro Title Services",
    amount: 450,
    expenseDate: ts(15).slice(0, 10),
    paymentStatus: "paid",
    createdAt: ts(15),
    updatedAt: ts(15),
  },
  {
    id: "exp-6",
    organizationId: "demo-org",
    leadId: "lead-demo-1",
    category: "printing_costs",
    vendor: "Local Print Shop",
    amount: 28,
    expenseDate: ts(8).slice(0, 10),
    paymentStatus: "paid",
    createdAt: ts(8),
    updatedAt: ts(8),
  },
];

export const DEMO_ACCRUED_MONEY: AccruedMoneyRecord[] = [
  {
    id: "acc-1",
    organizationId: "demo-org",
    leadId: "lead-demo-1",
    assignmentId: "asgn-1",
    targetAssignmentFee: 20000,
    agreedAssignmentFee: 18000,
    accruedAmount: 18000,
    accruedDate: ts(5),
    expectedPayoutDate: ts(-14),
    payoutMethod: "Title company wire",
    payoutStatus: "accrued_pending_closing",
    buyerName: "Jordan Blake / Blake Capital RE",
    titleCompany: "Lone Star Title Co.",
    attorneyReviewStatus: "recommended",
    closingStatus: "pending_confirmation",
    notes: "Accrued pending closing — not received",
    createdAt: ts(5),
    updatedAt: ts(2),
  },
  {
    id: "acc-2",
    organizationId: "demo-org",
    leadId: "lead-demo-2",
    assignmentId: "asgn-2",
    targetAssignmentFee: 12000,
    agreedAssignmentFee: null,
    accruedAmount: 0,
    payoutStatus: "potential_accrual",
    buyerName: "Morgan Ellis",
    attorneyReviewStatus: "required",
    closingStatus: "not_started",
    notes: "Potential accrual — buyer match in progress",
    createdAt: ts(10),
    updatedAt: ts(5),
  },
  {
    id: "acc-3",
    organizationId: "demo-org",
    leadId: "lead-demo-3",
    targetAssignmentFee: 10000,
    agreedAssignmentFee: 10000,
    accruedAmount: 10000,
    accruedDate: ts(20),
    expectedPayoutDate: ts(5),
    payoutMethod: "ACH",
    payoutStatus: "received",
    buyerName: "Riley Park",
    titleCompany: "Metro Title Services",
    attorneyReviewStatus: "completed",
    closingStatus: "closed",
    notes: "Manually recorded as received",
    createdAt: ts(20),
    updatedAt: ts(10),
  },
];
