import { GLOBAL_DISCLAIMER } from "@/lib/constants/disclaimer";
import type {
  AttorneyReviewItem,
  DocumentAuditLogEntry,
  DocumentRecord,
  DocumentWorkflowBlocker,
  LeadDocumentPacket,
  UploadedDocument,
} from "@/lib/types/documents";

const ts = (daysAgo: number) =>
  new Date(Date.now() - daysAgo * 86400000).toISOString();

export const DEMO_DOCUMENT_RECORDS: DocumentRecord[] = [
  {
    id: "doc-1", organizationId: "demo-org", leadId: "lead-demo-1",
    stateAbbreviation: "TX", countyName: "Harris", dealType: "direct_purchase",
    workflowStage: "under_contract", documentName: "Owner/Heir Verification Checklist",
    documentTypeId: "owner_heir_verification", documentCategory: "compliance_documents",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "reviewed", requiredStatus: "required", requiredReason: "Required before Under Contract",
    attorneyReviewFlag: false, attorneyReviewStatus: "not_required",
    signatureNeededFlag: false, signatureStatus: "not_required",
    sourceFieldsUsed: ["property_address", "owner_name", "state", "county"],
    templateId: "stpl-owner-heir", templateVersion: 1, fileUrl: null, uploadedFileReference: null,
    generatedContentSnapshot: "# Owner/Heir Verification Checklist\n\nProperty: 1842 Oak Hollow Ln, Houston, TX\nOwner: Margaret Chen Estate\n\n- [x] Public record verified\n- [x] Probate status researched",
    disclaimer: GLOBAL_DISCLAIMER, notes: null, archived: false, createdAt: ts(14), updatedAt: ts(3),
  },
  {
    id: "doc-2", organizationId: "demo-org", leadId: "lead-demo-1",
    stateAbbreviation: "TX", countyName: "Harris", dealType: "direct_purchase",
    workflowStage: "under_contract", documentName: "Property Research Worksheet",
    documentTypeId: "property_research_worksheet", documentCategory: "internal_worksheets",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "generated", requiredStatus: "required", requiredReason: "Required before Under Contract",
    attorneyReviewFlag: false, attorneyReviewStatus: "not_required",
    signatureNeededFlag: false, signatureStatus: "not_required",
    sourceFieldsUsed: ["property_address", "estimated_arv", "estate_lead_score"],
    templateId: "stpl-property-research", templateVersion: 1, fileUrl: null, uploadedFileReference: null,
    generatedContentSnapshot: "# Property Research Worksheet\n\nAddress: 1842 Oak Hollow Ln\nEstimated ARV: $285,000",
    disclaimer: GLOBAL_DISCLAIMER, notes: null, archived: false, createdAt: ts(12), updatedAt: ts(5),
  },
  {
    id: "doc-3", organizationId: "demo-org", leadId: "lead-demo-1",
    stateAbbreviation: "TX", countyName: "Harris", dealType: "direct_purchase",
    workflowStage: "under_contract", documentName: "Lead Source Record",
    documentTypeId: "lead_source_record", documentCategory: "source_records",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "uploaded", requiredStatus: "required", requiredReason: "Source documentation required",
    attorneyReviewFlag: false, attorneyReviewStatus: "not_required",
    signatureNeededFlag: false, signatureStatus: "not_required",
    sourceFieldsUsed: ["property_address", "lead_type"],
    templateId: "stpl-lead-source", templateVersion: 1, fileUrl: "/uploads/demo/source-record-tx.pdf",
    uploadedFileReference: "upload-1",
    generatedContentSnapshot: null,
    disclaimer: GLOBAL_DISCLAIMER, notes: "Harris County deed records attached", archived: false,
    createdAt: ts(10), updatedAt: ts(2),
  },
  {
    id: "doc-4", organizationId: "demo-org", leadId: "lead-demo-1",
    stateAbbreviation: "TX", countyName: "Harris", dealType: "direct_purchase",
    workflowStage: "under_contract", documentName: "Compliance Acknowledgement",
    documentTypeId: "compliance_acknowledgement", documentCategory: "compliance_documents",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "signed", requiredStatus: "required", requiredReason: "State compliance acknowledgement",
    attorneyReviewFlag: false, attorneyReviewStatus: "not_required",
    signatureNeededFlag: true, signatureStatus: "signed",
    sourceFieldsUsed: ["property_address", "state", "compliance_risk_level"],
    templateId: "stpl-compliance-ack", templateVersion: 1, fileUrl: null, uploadedFileReference: null,
    generatedContentSnapshot: "# Compliance Acknowledgement\n\nSigned by user on file.",
    disclaimer: GLOBAL_DISCLAIMER, notes: null, archived: false, createdAt: ts(8), updatedAt: ts(1),
  },
  {
    id: "doc-5", organizationId: "demo-org", leadId: "lead-demo-1",
    stateAbbreviation: "TX", countyName: "Harris", dealType: "direct_purchase",
    workflowStage: "under_contract", documentName: "Purchase Agreement Checklist",
    documentTypeId: "purchase_agreement_checklist", documentCategory: "seller_documents",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "needs_attorney_review", requiredStatus: "required",
    requiredReason: "Attorney review recommended for purchase workflow",
    attorneyReviewFlag: true, attorneyReviewStatus: "requested",
    signatureNeededFlag: false, signatureStatus: "not_required",
    sourceFieldsUsed: ["property_address", "state", "title_company"],
    templateId: "stpl-purchase-checklist", templateVersion: 1, fileUrl: null, uploadedFileReference: null,
    generatedContentSnapshot: "# PURCHASE AGREEMENT CHECKLIST — NOT A CONTRACT\n\nAttorney review pending.",
    disclaimer: GLOBAL_DISCLAIMER, notes: "Sent to attorney for review", archived: false,
    createdAt: ts(7), updatedAt: ts(1),
  },
  {
    id: "doc-6", organizationId: "demo-org", leadId: "lead-demo-1",
    stateAbbreviation: "TX", countyName: "Harris", dealType: "direct_purchase",
    workflowStage: "under_contract", documentName: "State Risk Acknowledgement",
    documentTypeId: "state_risk_acknowledgement", documentCategory: "compliance_documents",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "not_started", requiredStatus: "required", requiredReason: "TX elevated risk acknowledgement",
    attorneyReviewFlag: false, attorneyReviewStatus: "not_required",
    signatureNeededFlag: true, signatureStatus: "needed",
    sourceFieldsUsed: [], templateId: "stpl-state-risk", templateVersion: 1,
    fileUrl: null, uploadedFileReference: null, generatedContentSnapshot: null,
    disclaimer: GLOBAL_DISCLAIMER, notes: null, archived: false, createdAt: ts(6), updatedAt: ts(6),
  },
  {
    id: "doc-7", organizationId: "demo-org", leadId: "lead-demo-2",
    stateAbbreviation: "FL", countyName: "Orange", dealType: "assignment_of_contract",
    workflowStage: "assignment_sent", documentName: "Assignment Disclosure Checklist",
    documentTypeId: "assignment_disclosure_checklist", documentCategory: "compliance_documents",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "reviewed", requiredStatus: "required", requiredReason: "FL assignment disclosure",
    attorneyReviewFlag: true, attorneyReviewStatus: "acknowledged",
    signatureNeededFlag: false, signatureStatus: "not_required",
    sourceFieldsUsed: ["property_address", "state", "compliance_risk_level"],
    templateId: "stpl-assignment-disclosure", templateVersion: 1, fileUrl: null, uploadedFileReference: null,
    generatedContentSnapshot: "# Assignment Disclosure Checklist\n\nFL elevated risk acknowledged.",
    disclaimer: GLOBAL_DISCLAIMER, notes: null, archived: false, createdAt: ts(20), updatedAt: ts(4),
  },
  {
    id: "doc-8", organizationId: "demo-org", leadId: "lead-demo-2",
    stateAbbreviation: "FL", countyName: "Orange", dealType: "assignment_of_contract",
    workflowStage: "assignment_sent", documentName: "Buyer Profile Sheet",
    documentTypeId: "buyer_profile_sheet", documentCategory: "buyer_assignee_documents",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "draft", requiredStatus: "required", requiredReason: "Buyer matching required",
    attorneyReviewFlag: false, attorneyReviewStatus: "not_required",
    signatureNeededFlag: false, signatureStatus: "not_required",
    sourceFieldsUsed: ["buyer_name"],
    templateId: "stpl-buyer-profile", templateVersion: 1, fileUrl: null, uploadedFileReference: null,
    generatedContentSnapshot: "# Buyer Profile Sheet\n\nBuyer: [Buyer Name — Phase 6]",
    disclaimer: GLOBAL_DISCLAIMER, notes: "Awaiting buyer network match — Phase 6 placeholder", archived: false,
    createdAt: ts(15), updatedAt: ts(2),
  },
  {
    id: "doc-9", organizationId: "demo-org", leadId: "lead-demo-3",
    stateAbbreviation: "NC", countyName: "Wake", dealType: "direct_purchase",
    workflowStage: "offer_sent", documentName: "Purchase Offer Worksheet",
    documentTypeId: "purchase_offer_worksheet", documentCategory: "internal_worksheets",
    version: 1, createdBy: "Alex Morgan", updatedBy: "Alex Morgan",
    status: "generated", requiredStatus: "recommended", requiredReason: "Offer research worksheet",
    attorneyReviewFlag: false, attorneyReviewStatus: "not_required",
    signatureNeededFlag: false, signatureStatus: "not_required",
    sourceFieldsUsed: ["property_address", "offer_amount", "estimated_arv"],
    templateId: "stpl-purchase-offer", templateVersion: 1, fileUrl: null, uploadedFileReference: null,
    generatedContentSnapshot: "# Purchase Offer Worksheet — NOT A BINDING CONTRACT",
    disclaimer: GLOBAL_DISCLAIMER, notes: null, archived: false, createdAt: ts(5), updatedAt: ts(1),
  },
  {
    id: "doc-10", organizationId: "demo-org", leadId: null,
    stateAbbreviation: "TX", countyName: null, dealType: "direct_purchase",
    workflowStage: null, documentName: "Seller Intake Form (Template Sample)",
    documentTypeId: "seller_intake_form", documentCategory: "seller_documents",
    version: 1, createdBy: "SCS Nova", updatedBy: "SCS Nova",
    status: "generated", requiredStatus: "recommended", requiredReason: "Organization template sample",
    attorneyReviewFlag: false, attorneyReviewStatus: "not_required",
    signatureNeededFlag: true, signatureStatus: "not_required",
    sourceFieldsUsed: ["disclaimer"],
    templateId: "stpl-seller-intake", templateVersion: 1, fileUrl: null, uploadedFileReference: null,
    generatedContentSnapshot: "# Seller Intake Form — Workflow Template",
    disclaimer: GLOBAL_DISCLAIMER, notes: "Org-level sample — not attached to lead", archived: false,
    createdAt: ts(30), updatedAt: ts(30),
  },
];

export const DEMO_LEAD_PACKETS: LeadDocumentPacket[] = [
  {
    id: "pkt-1", organizationId: "demo-org", leadId: "lead-demo-1",
    stateAbbreviation: "TX", countyName: "Harris", dealType: "direct_purchase",
    packetStatus: "needs_attorney_review", readinessScore: 62, readinessBand: "Partially Ready",
    missingDocuments: ["State Risk Acknowledgement", "Source Document Packet", "Seller Disclosure Acknowledgement", "Purchase Offer Worksheet"],
    attorneyReviewItems: ["doc-5"],
    signedDocumentItems: ["doc-4"],
    uploadedDocumentItems: ["doc-3"],
    generatedDocumentItems: ["doc-1", "doc-2"],
    sourceRecordItems: ["doc-3"],
    documentRecordIds: ["doc-1", "doc-2", "doc-3", "doc-4", "doc-5", "doc-6"],
    createdAt: ts(14), updatedAt: ts(1),
  },
  {
    id: "pkt-2", organizationId: "demo-org", leadId: "lead-demo-2",
    stateAbbreviation: "FL", countyName: "Orange", dealType: "assignment_of_contract",
    packetStatus: "needs_documents", readinessScore: 48, readinessBand: "Needs Work",
    missingDocuments: ["Proof of Funds Record", "Assignment Agreement Checklist", "Title Company Intake Sheet"],
    attorneyReviewItems: [],
    signedDocumentItems: [],
    uploadedDocumentItems: [],
    generatedDocumentItems: ["doc-7", "doc-8"],
    sourceRecordItems: [],
    documentRecordIds: ["doc-7", "doc-8"],
    createdAt: ts(20), updatedAt: ts(2),
  },
  {
    id: "pkt-3", organizationId: "demo-org", leadId: "lead-demo-3",
    stateAbbreviation: "NC", countyName: "Wake", dealType: "direct_purchase",
    packetStatus: "building", readinessScore: 28, readinessBand: "Needs Work",
    missingDocuments: ["Owner/Heir Verification", "Lead Source Record", "Compliance Acknowledgement"],
    attorneyReviewItems: [],
    signedDocumentItems: [],
    uploadedDocumentItems: [],
    generatedDocumentItems: ["doc-9"],
    sourceRecordItems: [],
    documentRecordIds: ["doc-9"],
    createdAt: ts(5), updatedAt: ts(1),
  },
];

export const DEMO_UPLOADED_DOCUMENTS: UploadedDocument[] = [
  {
    id: "upload-1", organizationId: "demo-org", leadId: "lead-demo-1",
    uploadedBy: "Alex Morgan", fileName: "harris-deed-records.pdf", fileType: "pdf",
    fileSize: 245000, documentCategory: "source_records", documentTypeId: "lead_source_record",
    stateAbbreviation: "TX", status: "uploaded", attorneyReviewFlag: false,
    signatureNeededFlag: false, notes: "Harris County deed search results", createdAt: ts(10),
  },
  {
    id: "upload-2", organizationId: "demo-org", leadId: "lead-demo-2",
    uploadedBy: "Alex Morgan", fileName: "orange-probate-search.pdf", fileType: "pdf",
    fileSize: 128000, documentCategory: "source_records", documentTypeId: "probate_status_checklist",
    stateAbbreviation: "FL", status: "uploaded", attorneyReviewFlag: true,
    signatureNeededFlag: false, notes: "Orange County probate case search", createdAt: ts(18),
  },
];

export const DEMO_ATTORNEY_REVIEW_QUEUE: AttorneyReviewItem[] = [
  {
    id: "arv-1", organizationId: "demo-org", leadId: "lead-demo-1",
    documentRecordId: "doc-5", stateAbbreviation: "TX", countyName: "Harris",
    dealType: "direct_purchase", documentName: "Purchase Agreement Checklist",
    riskLevel: "elevated", reviewReason: "Template not attorney reviewed",
    templateReviewStatus: "approved", documentStatus: "needs_attorney_review",
    assignedReviewer: null, reviewStatus: "requested",
    notes: "User requested attorney review before proceeding", createdAt: ts(7), updatedAt: ts(1),
  },
  {
    id: "arv-2", organizationId: "demo-org", leadId: "lead-demo-2",
    documentRecordId: "doc-7", stateAbbreviation: "FL", countyName: "Orange",
    dealType: "assignment_of_contract", documentName: "Assignment Disclosure Checklist",
    riskLevel: "high", reviewReason: "Assignment workflow selected",
    templateReviewStatus: "attorney_reviewed", documentStatus: "reviewed",
    assignedReviewer: "Compliance Reviewer", reviewStatus: "acknowledged",
    notes: "FL assignment workflow — professional review acknowledged", createdAt: ts(20), updatedAt: ts(4),
  },
  {
    id: "arv-3", organizationId: "demo-org", leadId: "lead-demo-1",
    documentRecordId: "doc-6", stateAbbreviation: "TX", countyName: "Harris",
    dealType: "direct_purchase", documentName: "State Risk Acknowledgement",
    riskLevel: "elevated", reviewReason: "State risk Elevated",
    templateReviewStatus: "approved", documentStatus: "not_started",
    assignedReviewer: null, reviewStatus: "recommended",
    notes: "TX elevated compliance risk — acknowledgement not yet generated", createdAt: ts(6), updatedAt: ts(6),
  },
];

export const DEMO_DOCUMENT_AUDIT: DocumentAuditLogEntry[] = [
  { id: "da-1", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-1", documentRecordId: "doc-1", actionType: "generated", actionDescription: "Generated Owner/Heir Verification Checklist from template", previousValue: null, newValue: "generated", timestamp: ts(14) },
  { id: "da-2", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-1", documentRecordId: "doc-3", actionType: "uploaded", actionDescription: "Uploaded Harris County deed records", previousValue: "not_started", newValue: "uploaded", timestamp: ts(10) },
  { id: "da-3", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-1", documentRecordId: "doc-5", actionType: "attorney_review_requested", actionDescription: "Marked Purchase Agreement Checklist for attorney review", previousValue: "generated", newValue: "needs_attorney_review", timestamp: ts(7) },
  { id: "da-4", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-1", documentRecordId: "doc-4", actionType: "signed", actionDescription: "Compliance acknowledgement signed", previousValue: "generated", newValue: "signed", timestamp: ts(8) },
  { id: "da-5", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-2", documentRecordId: "doc-7", actionType: "reviewed", actionDescription: "Assignment disclosure checklist reviewed and acknowledged", previousValue: "generated", newValue: "reviewed", timestamp: ts(4) },
];

export const DEMO_DOCUMENT_BLOCKERS: DocumentWorkflowBlocker[] = [
  {
    id: "dwb-demo-1", organizationId: "demo-org", leadId: "lead-demo-1",
    documentRecordId: "doc-6", workflowStage: "under_contract",
    blockerType: "missing_document", blockerMessage: "State Risk Acknowledgement not started",
    requiredAction: "Generate and sign State Risk Acknowledgement", severity: "high",
    status: "active", createdAt: ts(3),
  },
  {
    id: "dwb-demo-2", organizationId: "demo-org", leadId: "lead-demo-1",
    documentRecordId: "doc-5", workflowStage: "under_contract",
    blockerType: "attorney_review", blockerMessage: "Purchase Agreement Checklist attorney review pending",
    requiredAction: "Complete attorney/title review tracking", severity: "medium",
    status: "active", createdAt: ts(2),
  },
];
