import type {
  FullLeadDetail,
  CommunicationLog,
  FollowUpReminder,
  DoNotContactRecord,
  LeadNote,
  CrmAuditEvent,
  LeadPipelineCard,
} from "@/lib/types/crm";

const ts = "2025-11-01T10:00:00Z";

function buildLead1(): FullLeadDetail {
  return {
    id: "lead-demo-1",
    organizationId: "demo-org",
    propertyAddress: "1842 Oakwood Dr, Houston, TX 77009",
    street: "1842 Oakwood Dr",
    city: "Houston",
    state: "TX",
    zip: "77009",
    county: "Harris",
    parcelId: "TX-HAR-1842-001",
    propertyType: "Single Family",
    beds: 3,
    baths: 2,
    squareFeet: 1650,
    lotSize: "0.18 acres",
    yearBuilt: 1962,
    estimatedValue: 245000,
    taxAssessedValue: 198500,
    lastSaleDate: "1996-04-12",
    lastSaleAmount: 89000,
    lastTransferDate: "2025-03-15",
    transferType: "Estate Transfer",
    deedType: "Warranty Deed",
    mortgageStatus: "No recent mortgage",
    mortgageAmount: null,
    mortgageDate: null,
    taxDelinquent: false,
    vacancySignal: true,
    listedStatus: false,
    ownerName: "Estate of M. Richardson",
    possibleHeirName: "S. Richardson",
    mailingAddress: "4201 Westheimer Rd, Phoenix, AZ 85004",
    primaryLeadType: "possible_inherited_property",
    secondaryLeadTypes: ["absentee_heir_lead", "vacant_estate_property"],
    estateLeadScore: 82,
    dealPotentialScore: 71,
    complianceRiskScore: 42,
    dataConfidenceScore: 78,
    scoreBand: "strong",
    positiveFactors: [
      "Recent ownership transfer",
      "Deed references estate language",
      "Out-of-state mailing address",
      "29 years prior ownership",
      "No recent mortgage found",
    ],
    negativeFactors: ["Heir contact not verified", "Probate status unconfirmed"],
    missingData: ["Heir phone number", "Probate case number", "Property condition photos"],
    manualVerificationNeeded: ["Owner/heir authority", "Probate status", "Vacancy confirmation"],
    signals: [
      { name: "Recent deed transfer", category: "transfer", explanation: "Transfer recorded March 2025", confidence: 92 },
      { name: "Estate deed language", category: "probate", explanation: "Deed references estate of prior owner", confidence: 85 },
      { name: "Out-of-state owner", category: "distress", explanation: "Mailing address in Arizona", confidence: 78 },
      { name: "Long ownership transfer", category: "inheritance", explanation: "Owned 29 years before transfer", confidence: 80 },
      { name: "Vacancy signal", category: "distress", explanation: "Utility and mail indicators suggest vacancy", confidence: 65 },
    ],
    sourceRecords: [
      {
        id: "src-1",
        sourceName: "Harris County Recorder",
        sourceType: "recorder_deed",
        sourceUrl: "https://example.gov/harris/recorder",
        retrievedAt: "2025-10-28T00:00:00Z",
        reliabilityScore: 82,
        freshnessScore: 75,
        permissionStatus: "approved_api",
        fieldsProvided: ["deed_type", "transfer_date", "owner_name"],
      },
      {
        id: "src-2",
        sourceName: "Harris Tax Assessor",
        sourceType: "tax_assessor",
        sourceUrl: "https://example.gov/harris/tax",
        retrievedAt: "2025-10-28T00:00:00Z",
        reliabilityScore: 78,
        freshnessScore: 70,
        permissionStatus: "approved_api",
        fieldsProvided: ["assessed_value", "mailing_address", "parcel_id"],
      },
    ],
    origin: "auto_discovered",
    pipelineStage: "contact_ready",
    assignedUserId: "demo-user",
    assignedUserName: "Alex Morgan",
    nextAction: "Review outreach caution and send soft inquiry",
    followUpDate: "2025-11-18",
    lastContactDate: null,
    doNotContact: false,
    dncReason: null,
    ownerHeir: {
      currentOwnerName: "Estate of M. Richardson",
      priorOwnerName: "M. Richardson",
      possibleHeirName: "S. Richardson",
      executorName: null,
      mailingAddress: "4201 Westheimer Rd, Phoenix, AZ 85004",
      propertyAddress: "1842 Oakwood Dr, Houston, TX 77009",
      ownerOccupiedStatus: "no",
      outOfStateOwner: "yes",
      mailingDiffersFromProperty: "yes",
      relationshipConfidence: 72,
      ownerVerificationStatus: "needs_research",
      heirVerificationStatus: "unknown",
      contactSource: "public_record",
      phone: null,
      email: null,
      consentStatus: "unknown",
      doNotContact: false,
      notes: "Heir may be out of state — verify before outreach",
    },
    demoRecord: true,
    createdAt: ts,
    updatedAt: "2025-11-10T14:00:00Z",
  };
}

function buildLead2(): FullLeadDetail {
  return {
    id: "lead-demo-2",
    organizationId: "demo-org",
    propertyAddress: "905 Riverside Ave, Jacksonville, FL 32204",
    street: "905 Riverside Ave",
    city: "Jacksonville",
    state: "FL",
    zip: "32204",
    county: "Duval",
    parcelId: "FL-DUV-905-002",
    propertyType: "Single Family",
    beds: 4,
    baths: 2,
    squareFeet: 1820,
    lotSize: "0.22 acres",
    yearBuilt: 1978,
    estimatedValue: 198000,
    taxAssessedValue: 165000,
    lastSaleDate: "2010-06-20",
    lastSaleAmount: 125000,
    lastTransferDate: "2025-08-01",
    transferType: "Quitclaim",
    deedType: "Quitclaim Deed",
    mortgageStatus: "Paid off",
    mortgageAmount: null,
    mortgageDate: "2018-03-01",
    taxDelinquent: true,
    vacancySignal: false,
    listedStatus: false,
    ownerName: "J. & K. Whitfield",
    possibleHeirName: "K. Whitfield",
    mailingAddress: "905 Riverside Ave, Jacksonville, FL 32204",
    primaryLeadType: "estate_transfer_lead",
    secondaryLeadTypes: ["tax_distress_estate_lead"],
    estateLeadScore: 76,
    dealPotentialScore: 65,
    complianceRiskScore: 68,
    dataConfidenceScore: 55,
    scoreBand: "strong",
    positiveFactors: ["Quitclaim after estate period", "Tax delinquency signal", "Family transfer pattern"],
    negativeFactors: ["County manual upload only", "Elevated state risk"],
    missingData: ["Executor documentation", "Tax payoff amount"],
    manualVerificationNeeded: ["Owner identity", "Tax delinquency amount", "Assignment disclosure requirements"],
    signals: [
      { name: "Quitclaim deed", category: "transfer", explanation: "Quitclaim recorded August 2025", confidence: 88 },
      { name: "Tax delinquency", category: "distress", explanation: "2 years delinquent per tax records", confidence: 90 },
      { name: "Family transfer", category: "inheritance", explanation: "Shared surname between prior and new owner", confidence: 70 },
    ],
    sourceRecords: [
      {
        id: "src-3",
        sourceName: "Duval CSV Import",
        sourceType: "csv_upload",
        sourceUrl: null,
        retrievedAt: "2025-10-15T00:00:00Z",
        reliabilityScore: 55,
        freshnessScore: 45,
        permissionStatus: "approved_csv_import",
        fieldsProvided: ["owner_name", "transfer_date", "tax_status"],
      },
    ],
    origin: "csv_imported",
    pipelineStage: "first_outreach_sent",
    assignedUserId: "demo-user",
    assignedUserName: "Alex Morgan",
    nextAction: "Complete follow-up — owner/heir verification pending",
    followUpDate: "2025-11-16",
    lastContactDate: "2025-11-08",
    doNotContact: false,
    dncReason: null,
    ownerHeir: {
      currentOwnerName: "J. & K. Whitfield",
      priorOwnerName: "R. Whitfield",
      possibleHeirName: "K. Whitfield",
      executorName: null,
      mailingAddress: "905 Riverside Ave, Jacksonville, FL 32204",
      propertyAddress: "905 Riverside Ave, Jacksonville, FL 32204",
      ownerOccupiedStatus: "unknown",
      outOfStateOwner: "no",
      mailingDiffersFromProperty: "no",
      relationshipConfidence: 68,
      ownerVerificationStatus: "partially_verified",
      heirVerificationStatus: "needs_research",
      contactSource: "csv_import",
      phone: null,
      email: null,
      consentStatus: "consent_needed",
      doNotContact: false,
      notes: "FL elevated risk — review disclosure before assignment",
    },
    demoRecord: true,
    createdAt: "2025-10-15T08:00:00Z",
    updatedAt: "2025-11-08T16:00:00Z",
  };
}

function buildLead3(): FullLeadDetail {
  return {
    id: "lead-demo-3",
    organizationId: "demo-org",
    propertyAddress: "3310 Providence Rd, Charlotte, NC 28211",
    street: "3310 Providence Rd",
    city: "Charlotte",
    state: "NC",
    zip: "28211",
    county: "Mecklenburg",
    parcelId: "NC-MEK-3310-003",
    propertyType: "Single Family",
    beds: 3,
    baths: 2.5,
    squareFeet: 2100,
    lotSize: "0.31 acres",
    yearBuilt: 1985,
    estimatedValue: 312000,
    taxAssessedValue: 275000,
    lastSaleDate: "2005-11-01",
    lastSaleAmount: 185000,
    lastTransferDate: "2025-09-20",
    transferType: "Trust Transfer",
    deedType: "Trust Deed",
    mortgageStatus: "No mortgage",
    mortgageAmount: null,
    mortgageDate: null,
    taxDelinquent: false,
    vacancySignal: true,
    listedStatus: false,
    ownerName: "Trust of A. Coleman",
    possibleHeirName: "B. Coleman",
    mailingAddress: "8820 Park Rd, Denver, CO 80209",
    primaryLeadType: "trust_transfer_lead",
    secondaryLeadTypes: ["vacant_estate_property"],
    estateLeadScore: 71,
    dealPotentialScore: 58,
    complianceRiskScore: 85,
    dataConfidenceScore: 30,
    scoreBand: "strong",
    positiveFactors: ["Trust transfer signal", "Vacancy indicator", "Long prior ownership"],
    negativeFactors: ["County research only", "Attorney review required", "Low data confidence"],
    missingData: ["Trust instrument details", "Trustee contact", "Beneficiary information"],
    manualVerificationNeeded: ["Trust authority", "Attorney review", "All contact information"],
    signals: [
      { name: "Trust transfer", category: "transfer", explanation: "Deed to family trust recorded September 2025", confidence: 82 },
      { name: "Vacancy signal", category: "distress", explanation: "Property appears unoccupied", confidence: 60 },
    ],
    sourceRecords: [
      {
        id: "src-4",
        sourceName: "Mecklenburg Research Feed",
        sourceType: "manual_research",
        sourceUrl: null,
        retrievedAt: "2025-10-01T00:00:00Z",
        reliabilityScore: 30,
        freshnessScore: 25,
        permissionStatus: "research_only",
        fieldsProvided: ["owner_name", "transfer_type"],
      },
    ],
    origin: "auto_discovered",
    pipelineStage: "needs_research",
    assignedUserId: "demo-user-2",
    assignedUserName: "Jordan Lee",
    nextAction: "Attorney review required before any outreach",
    followUpDate: null,
    lastContactDate: null,
    doNotContact: false,
    dncReason: null,
    ownerHeir: {
      currentOwnerName: "Trust of A. Coleman",
      priorOwnerName: "A. Coleman",
      possibleHeirName: "B. Coleman",
      executorName: null,
      mailingAddress: "8820 Park Rd, Denver, CO 80209",
      propertyAddress: "3310 Providence Rd, Charlotte, NC 28211",
      ownerOccupiedStatus: "no",
      outOfStateOwner: "yes",
      mailingDiffersFromProperty: "yes",
      relationshipConfidence: 55,
      ownerVerificationStatus: "manual_review_required",
      heirVerificationStatus: "unknown",
      contactSource: "unknown",
      phone: null,
      email: null,
      consentStatus: "manual_review_required",
      doNotContact: false,
      notes: "NC attorney review required — do not outreach until cleared",
    },
    demoRecord: true,
    createdAt: "2025-10-01T12:00:00Z",
    updatedAt: "2025-11-05T09:00:00Z",
  };
}

function buildLead4Dnc(): FullLeadDetail {
  return {
    ...buildLead2(),
    id: "lead-demo-4",
    propertyAddress: "220 Peachtree St NE, Atlanta, GA 30303",
    street: "220 Peachtree St NE",
    city: "Atlanta",
    state: "GA",
    zip: "30303",
    county: "Fulton",
    parcelId: "GA-FUL-220-004",
    ownerName: "C. Patterson",
    primaryLeadType: "family_transfer_lead",
    estateLeadScore: 58,
    pipelineStage: "do_not_contact",
    doNotContact: true,
    dncReason: "Requested no contact",
    nextAction: "Outreach disabled — audit trail only",
    ownerHeir: {
      ...buildLead2().ownerHeir,
      currentOwnerName: "C. Patterson",
      doNotContact: true,
      consentStatus: "do_not_contact",
    },
  };
}

export const DEMO_FULL_LEADS: FullLeadDetail[] = [
  buildLead1(),
  buildLead2(),
  buildLead3(),
  buildLead4Dnc(),
];

export const DEMO_COMMUNICATION_LOGS: CommunicationLog[] = [
  {
    id: "comm-1",
    leadId: "lead-demo-2",
    organizationId: "demo-org",
    userId: "demo-user",
    userName: "Alex Morgan",
    communicationDate: "2025-11-08",
    communicationTime: "10:30",
    contactMethod: "voicemail",
    contactPerson: "J. Whitfield",
    contactRole: "owner",
    templateUsedId: "tpl-voicemail",
    templateUsedName: "Voicemail Script",
    messageBodySnapshot: "Hi, this is Alex Morgan. I'm calling about the property at 905 Riverside Ave, Jacksonville, FL 32204. I wanted to see if selling it as-is is something you would ever consider. No pressure at all.",
    outcome: "left_voicemail",
    followUpDate: "2025-11-16",
    consentStatus: "consent_needed",
    dncStatus: false,
    stateOutreachWarningReviewed: true,
    dncReminderAcknowledged: true,
    notes: "Left respectful voicemail per approved template",
    createdAt: "2025-11-08T10:30:00Z",
  },
  {
    id: "comm-2",
    leadId: "lead-demo-1",
    organizationId: "demo-org",
    userId: "demo-user",
    userName: "Alex Morgan",
    communicationDate: "2025-11-05",
    communicationTime: "14:00",
    contactMethod: "internal_note",
    contactPerson: "N/A",
    contactRole: "unknown",
    templateUsedId: null,
    templateUsedName: null,
    messageBodySnapshot: "Reviewed Harris County deed records. Estate transfer confirmed. Heir appears to be out of state.",
    outcome: "internal_note_only",
    followUpDate: null,
    consentStatus: "not_applicable",
    dncStatus: false,
    stateOutreachWarningReviewed: true,
    dncReminderAcknowledged: true,
    notes: "Research note — no outreach attempted",
    createdAt: "2025-11-05T14:00:00Z",
  },
];

export const DEMO_FOLLOW_UPS: FollowUpReminder[] = [
  {
    id: "fu-1",
    leadId: "lead-demo-2",
    organizationId: "demo-org",
    assignedUserId: "demo-user",
    assignedUserName: "Alex Morgan",
    propertyAddress: "905 Riverside Ave, Jacksonville, FL 32204",
    followUpDate: "2025-11-16",
    followUpTime: "10:00",
    followUpMethod: "call",
    reason: "Voicemail follow-up",
    priority: "normal",
    status: "scheduled",
    relatedCommunicationId: "comm-1",
    notes: "Second contact attempt if no response",
    createdAt: "2025-11-08T10:35:00Z",
    completedAt: null,
  },
  {
    id: "fu-2",
    leadId: "lead-demo-1",
    organizationId: "demo-org",
    assignedUserId: "demo-user",
    assignedUserName: "Alex Morgan",
    propertyAddress: "1842 Oakwood Dr, Houston, TX 77009",
    followUpDate: "2025-11-18",
    followUpTime: null,
    followUpMethod: "direct_mail",
    reason: "Initial soft inquiry",
    priority: "normal",
    status: "scheduled",
    relatedCommunicationId: null,
    notes: "Send soft inquiry letter after DNC screening",
    createdAt: "2025-11-10T09:00:00Z",
    completedAt: null,
  },
];

export const DEMO_DNC_RECORDS: DoNotContactRecord[] = [
  {
    id: "dnc-1",
    leadId: "lead-demo-4",
    organizationId: "demo-org",
    contactPerson: "C. Patterson",
    contactMethod: "phone",
    reason: "Requested no contact",
    source: "conversation",
    setByUserId: "demo-user",
    setByUserName: "Alex Morgan",
    setAt: "2025-11-01T11:00:00Z",
    notes: "Contact requested removal from all outreach lists",
    active: true,
  },
];

export const DEMO_NOTES: LeadNote[] = [
  {
    id: "note-1",
    leadId: "lead-demo-1",
    organizationId: "demo-org",
    userId: "demo-user",
    userName: "Alex Morgan",
    noteType: "research",
    body: "Deed shows estate transfer from M. Richardson to S. Richardson. Mailing address is Phoenix, AZ. Property appears vacant based on utility records.",
    visibility: "internal_team",
    pinned: true,
    edited: false,
    createdAt: "2025-11-05T14:05:00Z",
    updatedAt: "2025-11-05T14:05:00Z",
  },
  {
    id: "note-2",
    leadId: "lead-demo-3",
    organizationId: "demo-org",
    userId: "demo-user-2",
    userName: "Jordan Lee",
    noteType: "compliance",
    body: "NC Mecklenburg county is research-only. Attorney review required before any outreach. Do not contact until cleared.",
    visibility: "compliance_reviewers",
    pinned: true,
    edited: false,
    createdAt: "2025-11-05T09:30:00Z",
    updatedAt: "2025-11-05T09:30:00Z",
  },
];

export const DEMO_CRM_AUDIT: CrmAuditEvent[] = [
  { id: "evt-1", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-2", eventType: "communication_logged", previousValue: null, newValue: "voicemail", eventDescription: "Voicemail logged using approved template", timestamp: "2025-11-08T10:30:00Z", relatedModule: "outreach", riskLevel: "moderate" },
  { id: "evt-2", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-2", eventType: "pipeline_stage_changed", previousValue: "contact_ready", newValue: "first_outreach_sent", eventDescription: "Stage changed to First Outreach Sent", timestamp: "2025-11-08T10:35:00Z", relatedModule: "pipeline", riskLevel: null },
  { id: "evt-3", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-4", eventType: "do_not_contact_set", previousValue: "contact_ready", newValue: "do_not_contact", eventDescription: "Do Not Contact set — requested no contact", timestamp: "2025-11-01T11:00:00Z", relatedModule: "outreach", riskLevel: null },
  { id: "evt-4", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-2", eventType: "outreach_template_blocked", previousValue: null, newValue: "blocked", eventDescription: "Template blocked: contained grief-exploiting phrase", timestamp: "2025-11-07T09:00:00Z", relatedModule: "outreach_safety", riskLevel: "elevated" },
  { id: "evt-5", organizationId: "demo-org", userId: "demo-user", userName: "Alex Morgan", leadId: "lead-demo-1", eventType: "note_added", previousValue: null, newValue: "research", eventDescription: "Research note added", timestamp: "2025-11-05T14:05:00Z", relatedModule: "notes", riskLevel: null },
];

export function toPipelineCard(lead: FullLeadDetail, hasBlocker = false): LeadPipelineCard {
  return {
    id: lead.id,
    propertyAddress: lead.propertyAddress,
    leadType: lead.primaryLeadType,
    estateLeadScore: lead.estateLeadScore,
    complianceRiskScore: lead.complianceRiskScore,
    assignedUserName: lead.assignedUserName,
    nextAction: lead.nextAction,
    followUpDate: lead.followUpDate,
    lastContactDate: lead.lastContactDate,
    pipelineStage: lead.pipelineStage,
    hasBlocker,
    doNotContact: lead.doNotContact,
  };
}

export const DEMO_BLOCKED_TEMPLATE_EXAMPLE = {
  attempted: "I know someone died and you probably need to sell the property fast.",
  result: "blocked",
  reason: "Grief-exploiting and pressure language detected",
  suggested: "I'm reaching out about the property at [address] to see if selling it as-is is something you would ever consider. No pressure either way.",
};
