import { US_STATES } from "@/lib/constants/us-states";
import type {
  StateProfile,
  CountyProfile,
  ComplianceAcknowledgement,
  WorkflowBlocker,
  ComplianceAuditLogEntry,
  LeadComplianceContext,
} from "@/lib/types/compliance";

const ts = "2025-11-15T10:00:00Z";

function defaultStateProfile(
  name: string,
  abbr: string,
  overrides: Partial<StateProfile> = {}
): StateProfile {
  return {
    id: `state-${abbr.toLowerCase()}`,
    stateName: name,
    stateAbbreviation: abbr,
    supportedStatus: "research_only",
    complianceReviewStatus: "not_reviewed",
    lastReviewedAt: null,
    legalSourceLinks: [
      { label: `${name} Secretary of State`, url: `https://example.gov/${abbr.toLowerCase()}/sos` },
      { label: `${name} Property Records Portal`, url: `https://example.gov/${abbr.toLowerCase()}/records` },
    ],
    attorneyReviewStatus: "not_reviewed",
    wholesalingDisclosureNotes: "Disclosure requirements vary. Confirm with qualified professional.",
    assignmentContractNotes: "Assignment rules may vary. Review with attorney before marketing contract interest.",
    marketingContractInterestWarning: "Market your contract interest only — not the property itself unless properly licensed.",
    licensingRiskLevel: "moderate",
    sellerDisclosureChecklist: ["Property condition disclosure", "Lead-based paint if applicable"],
    buyerAssigneeDisclosureChecklist: ["Assignment interest disclosure", "Profit disclosure where applicable"],
    requiredFormsChecklist: ["Purchase agreement", "Assignment agreement if applicable"],
    recommendedProfessionalContacts: ["Licensed real estate attorney", "Title company", "Licensed broker if referral needed"],
    titleCompanyNotes: "Use a licensed title company familiar with local recording requirements.",
    recordingOfficeNotes: "Confirm recording office requirements for deed and assignment documents.",
    probateCourtAccessNotes: "Probate records access varies by county. Manual verification may be required.",
    countySourceCoverage: "Varies by county — see county profiles",
    dataAvailabilityRating: "limited",
    riskRating: "moderate",
    userWarnings: [
      "Demo compliance data is fictional and for product demonstration only.",
      "EstateLeadOS cannot confirm legal compliance for this state.",
    ],
    outreachCaution: "Follow applicable call, text, and mail consent requirements.",
    recordingConsentReminder: null,
    callTextRestrictions: null,
    active: true,
    createdAt: ts,
    updatedAt: ts,
    ...overrides,
  };
}

const DEMO_STATE_OVERRIDES: Record<string, Partial<StateProfile>> = {
  TX: {
    supportedStatus: "partially_supported",
    complianceReviewStatus: "reviewed_internally",
    lastReviewedAt: "2025-10-01T00:00:00Z",
    dataAvailabilityRating: "moderate",
    riskRating: "moderate",
    licensingRiskLevel: "moderate",
    countySourceCoverage: "Harris, Dallas, Tarrant — partial API support",
    userWarnings: [
      "Demo compliance data is fictional and for product demonstration only.",
      "Texas assignment and disclosure rules require professional review.",
    ],
    outreachCaution: "Review Texas call/text consent requirements before outreach.",
    recordingConsentReminder: "Texas is a one-party consent state for many recordings — confirm applicability.",
  },
  FL: {
    supportedStatus: "partially_supported",
    complianceReviewStatus: "in_review",
    lastReviewedAt: "2025-09-15T00:00:00Z",
    dataAvailabilityRating: "moderate",
    riskRating: "elevated",
    licensingRiskLevel: "elevated",
    userWarnings: [
      "Demo compliance data is fictional and for product demonstration only.",
      "Florida has heightened disclosure and licensing considerations.",
    ],
    outreachCaution: "Florida has specific telemarketing and solicitation rules.",
    callTextRestrictions: "Review Florida call and text solicitation requirements.",
  },
  OH: {
    supportedStatus: "fully_supported",
    complianceReviewStatus: "reviewed_internally",
    lastReviewedAt: "2025-11-01T00:00:00Z",
    dataAvailabilityRating: "strong",
    riskRating: "low",
    licensingRiskLevel: "low",
    countySourceCoverage: "Franklin, Cuyahoga — API supported",
  },
  GA: {
    supportedStatus: "research_only",
    complianceReviewStatus: "research_only",
    riskRating: "moderate",
    dataAvailabilityRating: "limited",
    userWarnings: ["Demo data only. Georgia rules require attorney review."],
  },
  NC: {
    supportedStatus: "attorney_review_required",
    complianceReviewStatus: "needs_update",
    riskRating: "attorney_review_required",
    licensingRiskLevel: "high",
    userWarnings: [
      "Demo compliance data is fictional.",
      "North Carolina marked attorney review required in demo.",
    ],
  },
};

export function generateAllStateProfiles(): StateProfile[] {
  return US_STATES.map((s) =>
    defaultStateProfile(s.name, s.abbreviation, DEMO_STATE_OVERRIDES[s.abbreviation] ?? {})
  );
}

export const DEMO_COUNTIES: CountyProfile[] = [
  {
    id: "county-harris-tx",
    stateProfileId: "state-tx",
    stateAbbreviation: "TX",
    countyName: "Harris",
    supportedStatus: "api_supported",
    dataSourceCoverage: "Tax assessor, recorder partial",
    recorderAccessStatus: "approved_api",
    taxAssessorAccessStatus: "approved_api",
    probateCourtAccessStatus: "manual_only",
    registerOfWillsAccessStatus: null,
    publicNoticeAccessStatus: "manual_only",
    manualUploadAvailability: true,
    dataReliabilityScore: 78,
    dataFreshnessScore: 72,
    countyRiskRating: "moderate",
    countyNotes: "Demo county profile — fictional data.",
    sourceLinks: [{ label: "Harris County Clerk", url: "https://example.gov/harris/clerk" }],
    lastReviewedAt: "2025-10-01T00:00:00Z",
    adminApprovalStatus: "approved",
    active: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "county-dallas-tx",
    stateProfileId: "state-tx",
    stateAbbreviation: "TX",
    countyName: "Dallas",
    supportedStatus: "csv_import_supported",
    dataSourceCoverage: "CSV import, manual research",
    recorderAccessStatus: "approved_manual",
    taxAssessorAccessStatus: "approved_api",
    probateCourtAccessStatus: "limited",
    registerOfWillsAccessStatus: null,
    publicNoticeAccessStatus: "research_only",
    manualUploadAvailability: true,
    dataReliabilityScore: 65,
    dataFreshnessScore: 58,
    countyRiskRating: "moderate",
    countyNotes: "Demo — probate access limited.",
    sourceLinks: [],
    lastReviewedAt: "2025-09-01T00:00:00Z",
    adminApprovalStatus: "approved",
    active: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "county-franklin-oh",
    stateProfileId: "state-oh",
    stateAbbreviation: "OH",
    countyName: "Franklin",
    supportedStatus: "api_supported",
    dataSourceCoverage: "Full API support demo",
    recorderAccessStatus: "approved_api",
    taxAssessorAccessStatus: "approved_api",
    probateCourtAccessStatus: "approved_manual",
    registerOfWillsAccessStatus: null,
    publicNoticeAccessStatus: "approved_manual",
    manualUploadAvailability: true,
    dataReliabilityScore: 88,
    dataFreshnessScore: 85,
    countyRiskRating: "low",
    countyNotes: "Demo fully supported county.",
    sourceLinks: [{ label: "Franklin County Records", url: "https://example.gov/franklin" }],
    lastReviewedAt: "2025-11-01T00:00:00Z",
    adminApprovalStatus: "approved",
    active: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "county-duval-fl",
    stateProfileId: "state-fl",
    stateAbbreviation: "FL",
    countyName: "Duval",
    supportedStatus: "manual_upload_only",
    dataSourceCoverage: "Manual upload and CSV only",
    recorderAccessStatus: "approved_manual",
    taxAssessorAccessStatus: "approved_manual",
    probateCourtAccessStatus: "limited",
    registerOfWillsAccessStatus: null,
    publicNoticeAccessStatus: "unknown",
    manualUploadAvailability: true,
    dataReliabilityScore: 55,
    dataFreshnessScore: 45,
    countyRiskRating: "elevated",
    countyNotes: "Demo — manual upload only. No automated pulling.",
    sourceLinks: [],
    lastReviewedAt: "2025-08-01T00:00:00Z",
    adminApprovalStatus: "approved",
    active: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "county-mecklenburg-nc",
    stateProfileId: "state-nc",
    stateAbbreviation: "NC",
    countyName: "Mecklenburg",
    supportedStatus: "research_only",
    dataSourceCoverage: "Research only — no automated access",
    recorderAccessStatus: "research_only",
    taxAssessorAccessStatus: "research_only",
    probateCourtAccessStatus: "limited",
    registerOfWillsAccessStatus: null,
    publicNoticeAccessStatus: "blocked",
    manualUploadAvailability: true,
    dataReliabilityScore: 30,
    dataFreshnessScore: 25,
    countyRiskRating: "attorney_review_required",
    countyNotes: "Demo — attorney review required.",
    sourceLinks: [],
    lastReviewedAt: null,
    adminApprovalStatus: "pending",
    active: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "county-fulton-ga",
    stateProfileId: "state-ga",
    stateAbbreviation: "GA",
    countyName: "Fulton",
    supportedStatus: "unknown",
    dataSourceCoverage: "Unknown — pending SCS Nova review",
    recorderAccessStatus: "unknown",
    taxAssessorAccessStatus: "unknown",
    probateCourtAccessStatus: "unknown",
    registerOfWillsAccessStatus: null,
    publicNoticeAccessStatus: "unknown",
    manualUploadAvailability: true,
    dataReliabilityScore: 0,
    dataFreshnessScore: 0,
    countyRiskRating: "moderate",
    countyNotes: "Demo — unknown status blocks automated access.",
    sourceLinks: [],
    lastReviewedAt: null,
    adminApprovalStatus: "pending",
    active: true,
    createdAt: ts,
    updatedAt: ts,
  },
];

export const DEMO_ACKNOWLEDGEMENTS: ComplianceAcknowledgement[] = [
  {
    id: "ack-1",
    userId: "demo-user",
    organizationId: "demo-org",
    leadId: "lead-demo-1",
    stateProfileId: "state-tx",
    countyProfileId: "county-harris-tx",
    acknowledgementType: "general_compliance",
    acknowledgementText: "I understand EstateLeadOS does not provide legal, tax, brokerage, financial, or investment advice.",
    relatedRiskLevel: "moderate",
    relatedWorkflowStage: "under_contract",
    timestamp: "2025-11-10T14:00:00Z",
    devicePlaceholder: "demo-device",
    version: "1.0",
    active: true,
  },
];

export const DEMO_WORKFLOW_BLOCKERS: WorkflowBlocker[] = [
  {
    id: "blk-demo-1",
    leadId: "lead-demo-1",
    stateProfileId: "state-fl",
    countyProfileId: "county-duval-fl",
    workflowStage: "under_contract",
    blockerType: "missing_document",
    blockerMessage: "Owner/heir verification checklist is not complete.",
    requiredAction: "Complete owner/heir verification checklist.",
    severity: "blocking",
    status: "active",
    createdAt: "2025-11-12T09:00:00Z",
    resolvedAt: null,
    resolvedBy: null,
  },
  {
    id: "blk-demo-2",
    leadId: "lead-demo-2",
    stateProfileId: "state-nc",
    countyProfileId: "county-mecklenburg-nc",
    workflowStage: "assignment_sent",
    blockerType: "attorney_review",
    blockerMessage: "Attorney review required for North Carolina assignment workflow.",
    requiredAction: "Acknowledge attorney review reminder.",
    severity: "elevated",
    status: "active",
    createdAt: "2025-11-11T11:00:00Z",
    resolvedAt: null,
    resolvedBy: null,
  },
  {
    id: "blk-demo-3",
    leadId: "lead-demo-3",
    stateProfileId: "state-nc",
    countyProfileId: "county-mecklenburg-nc",
    workflowStage: "under_contract",
    blockerType: "restricted_risk",
    blockerMessage: "Compliance risk is Restricted. Workflow movement blocked.",
    requiredAction: "Contact Compliance Reviewer.",
    severity: "restricted",
    status: "active",
    createdAt: "2025-11-13T08:00:00Z",
    resolvedAt: null,
    resolvedBy: null,
  },
];

export const DEMO_COMPLIANCE_AUDIT: ComplianceAuditLogEntry[] = [
  {
    id: "audit-1",
    organizationId: "demo-org",
    userId: "demo-user",
    leadId: "lead-demo-1",
    actionType: "compliance_check",
    actionDescription: "Compliance check run for TX/Harris",
    previousValue: null,
    newValue: "moderate",
    riskLevel: "moderate",
    timestamp: "2025-11-10T14:00:00Z",
  },
  {
    id: "audit-2",
    organizationId: "demo-org",
    userId: "demo-user",
    leadId: "lead-demo-1",
    actionType: "acknowledgement",
    actionDescription: "General compliance acknowledgement recorded",
    previousValue: null,
    newValue: "complete",
    riskLevel: "moderate",
    timestamp: "2025-11-10T14:05:00Z",
  },
];

export const DEMO_LEAD_COMPLIANCE: LeadComplianceContext[] = [
  {
    leadId: "lead-demo-1",
    stateAbbreviation: "TX",
    countyName: "Harris",
    dealType: "direct_purchase",
    acquisitionStrategy: "direct_acquisition",
    complianceRiskScore: 42,
    complianceRiskLevel: "moderate",
    ownerIdentityVerified: false,
    sourceDocumentsAttached: true,
    communicationLogActive: false,
    equipmentProgress: 45,
    documentProgress: 30,
    acknowledgements: [DEMO_ACKNOWLEDGEMENTS[0]],
    blockers: [],
    lastComplianceCheck: null,
  },
  {
    leadId: "lead-demo-2",
    stateAbbreviation: "FL",
    countyName: "Duval",
    dealType: "assignment_of_contract",
    acquisitionStrategy: "contract_assignment",
    complianceRiskScore: 68,
    complianceRiskLevel: "elevated",
    ownerIdentityVerified: false,
    sourceDocumentsAttached: false,
    communicationLogActive: false,
    equipmentProgress: 20,
    documentProgress: 10,
    acknowledgements: [],
    blockers: [DEMO_WORKFLOW_BLOCKERS[0]],
    lastComplianceCheck: null,
  },
  {
    leadId: "lead-demo-3",
    stateAbbreviation: "NC",
    countyName: "Mecklenburg",
    dealType: "needs_attorney_review",
    acquisitionStrategy: "attorney_review",
    complianceRiskScore: 85,
    complianceRiskLevel: "restricted",
    ownerIdentityVerified: false,
    sourceDocumentsAttached: false,
    communicationLogActive: false,
    equipmentProgress: 5,
    documentProgress: 0,
    acknowledgements: [],
    blockers: [DEMO_WORKFLOW_BLOCKERS[2], DEMO_WORKFLOW_BLOCKERS[1]],
    lastComplianceCheck: null,
  },
];

// Lead summaries are sourced from demo-crm.ts via crm service
export const DEMO_LEADS_SUMMARY: {
  id: string;
  propertyAddress: string;
  ownerName: string;
  state: string;
  county: string;
  leadType: string;
  estateLeadScore: number;
  dealPotentialScore: number;
  complianceRiskScore: number;
  dataConfidenceScore: number;
  status: string;
  origin: "auto_discovered" | "csv_imported" | "manually_added" | "demo";
}[] = [];
