import type { DashboardMetrics } from "@/lib/types";

export const DEMO_DASHBOARD_METRICS: DashboardMetrics = {
  totalEstateLeads: 1247,
  newLeadsThisWeek: 89,
  highScoreLeads: 156,
  leadsByState: [
    { state: "TX", count: 312 },
    { state: "FL", count: 278 },
    { state: "OH", count: 189 },
    { state: "GA", count: 156 },
    { state: "NC", count: 134 },
    { state: "PA", count: 98 },
    { state: "AZ", count: 80 },
  ],
  leadsByCounty: [
    { county: "Harris", state: "TX", count: 89 },
    { county: "Maricopa", state: "AZ", count: 67 },
    { county: "Franklin", state: "OH", count: 54 },
    { county: "Duval", state: "FL", count: 48 },
    { county: "Mecklenburg", state: "NC", count: 42 },
  ],
  leadsNeedingComplianceReview: 23,
  leadsReadyForOutreach: 187,
  leadsUnderContract: 14,
  estimatedPipelineSpread: 428500,
  documentsPending: 31,
  followUpsDue: 18,
  riskAlerts: 7,
  supportedStates: 42,
  supportedCounties: 318,
  dataSourceHealth: "healthy",
  systemStatus: "operational",
  assignmentSummary: { active: 6, closing: 2, closed: 3 },
  buyerMatchingActivity: 14,
  documentReadinessPercent: 72,
  usageLimitPercent: 7,
  planName: "Team",
  planStatus: "Active",
  openSupportTickets: 4,
};

export const FRESH_START_DASHBOARD_METRICS: DashboardMetrics = {
  totalEstateLeads: 0,
  newLeadsThisWeek: 0,
  highScoreLeads: 0,
  leadsByState: [],
  leadsByCounty: [],
  leadsNeedingComplianceReview: 0,
  leadsReadyForOutreach: 0,
  leadsUnderContract: 0,
  estimatedPipelineSpread: 0,
  documentsPending: 0,
  followUpsDue: 0,
  riskAlerts: 0,
  supportedStates: 0,
  supportedCounties: 0,
  dataSourceHealth: "healthy",
  systemStatus: "operational",
  assignmentSummary: { active: 0, closing: 0, closed: 0 },
  buyerMatchingActivity: 0,
  documentReadinessPercent: 0,
  usageLimitPercent: 0,
  planName: "Starter",
  planStatus: "Trial",
  openSupportTickets: 0,
};
