import type { SourceRegistryEntry } from "@/lib/types/government";

export const REJECTED_MARKETPLACE_DOMAINS = [
  "zillow.com",
  "realtor.com",
  "redfin.com",
  "trulia.com",
  "homes.com",
  "auction.com",
  "foreclosure.com",
  "propstream.com",
  "batchleads.io",
  "dealmachine.com",
  "privy.com",
  "roofstock.com",
  "movoto.com",
  "apartments.com",
  "hotpads.com",
  "landwatch.com",
  "landandfarm.com",
] as const;

export const GOVERNMENT_DOMAIN_PATTERNS = [
  /\.gov$/i,
  /\.gov\./i,
  /maryland\.gov/i,
  /mdlandrec\.net/i,
  /sdat\.dat\.maryland\.gov/i,
  /registers\.maryland\.gov/i,
  /harfordcountymd\.gov/i,
  /data\.maryland\.gov/i,
] as const;

export const MARYLAND_SOURCE_REGISTRY_SEED: Omit<SourceRegistryEntry, "id" | "createdAt">[] = [
  {
    sourceName: "Maryland SDAT Real Property Search",
    sourceType: "property_assessment",
    jurisdictionState: "MD",
    jurisdictionCounty: null,
    baseUrl: "https://sdat.dat.maryland.gov/",
    isGovernmentSource: true,
    trustLevel: "official",
    allowedForLeadCreation: true,
    requiresManualLogin: false,
    notes: "State Department of Assessments and Taxation",
  },
  {
    sourceName: "Maryland Land Records (MDLandRec)",
    sourceType: "deed_land_record",
    jurisdictionState: "MD",
    jurisdictionCounty: null,
    baseUrl: "https://mdlandrec.net/",
    isGovernmentSource: true,
    trustLevel: "official",
    allowedForLeadCreation: true,
    requiresManualLogin: true,
    notes: "Official Maryland land records",
  },
  {
    sourceName: "Maryland Register of Wills Estate Search",
    sourceType: "probate_estate",
    jurisdictionState: "MD",
    jurisdictionCounty: null,
    baseUrl: "https://registers.maryland.gov/",
    isGovernmentSource: true,
    trustLevel: "official",
    allowedForLeadCreation: true,
    requiresManualLogin: false,
    notes: "Official estate and probate case search",
  },
  {
    sourceName: "Harford County GIS Parcel Map",
    sourceType: "gis_parcel_map",
    jurisdictionState: "MD",
    jurisdictionCounty: "Harford",
    baseUrl: "https://gis.harfordcountymd.gov/",
    isGovernmentSource: true,
    trustLevel: "official",
    allowedForLeadCreation: true,
    requiresManualLogin: false,
    notes: "Official Harford County parcel GIS",
  },
  {
    sourceName: "Harford County Treasury / Property Tax",
    sourceType: "tax_record",
    jurisdictionState: "MD",
    jurisdictionCounty: "Harford",
    baseUrl: "https://www.harfordcountymd.gov/",
    isGovernmentSource: true,
    trustLevel: "official_secondary",
    allowedForLeadCreation: true,
    requiresManualLogin: false,
    notes: "Harford County official property tax",
  },
  {
    sourceName: "Maryland Open Data Portal",
    sourceType: "open_data",
    jurisdictionState: "MD",
    jurisdictionCounty: null,
    baseUrl: "https://data.maryland.gov/",
    isGovernmentSource: true,
    trustLevel: "official_secondary",
    allowedForLeadCreation: true,
    requiresManualLogin: false,
    notes: "Official Maryland open-data property datasets",
  },
];

export const REJECTED_REGISTRY_SEED: Omit<SourceRegistryEntry, "id" | "createdAt">[] = [
  { sourceName: "Zillow", sourceType: "marketplace_listing", jurisdictionState: null, jurisdictionCounty: null, baseUrl: "https://www.zillow.com/", isGovernmentSource: false, trustLevel: "rejected", allowedForLeadCreation: false, requiresManualLogin: false, notes: "Marketplace" },
  { sourceName: "Realtor.com", sourceType: "marketplace_listing", jurisdictionState: null, jurisdictionCounty: null, baseUrl: "https://www.realtor.com/", isGovernmentSource: false, trustLevel: "rejected", allowedForLeadCreation: false, requiresManualLogin: false, notes: "Marketplace" },
  { sourceName: "Redfin", sourceType: "marketplace_listing", jurisdictionState: null, jurisdictionCounty: null, baseUrl: "https://www.redfin.com/", isGovernmentSource: false, trustLevel: "rejected", allowedForLeadCreation: false, requiresManualLogin: false, notes: "Marketplace" },
];
