import type { ModuleStatus } from "@/lib/types";

export const MODULE_REGISTRY: ModuleStatus[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    phase: 1,
    status: "active",
    description: "Operational overview and pipeline metrics",
  },
  {
    id: "lead-discovery",
    name: "Lead Discovery Engine",
    phase: 2,
    status: "active",
    description: "Internet search for probate and inherited property leads",
  },
  {
    id: "market-search",
    name: "Market Search",
    phase: 2,
    status: "active",
    description: "Internet lead search and market filters",
  },
  {
    id: "lead-feed",
    name: "Lead Feed",
    phase: 2,
    status: "active",
    description: "Scored estate and inherited property leads from internet search",
  },
  {
    id: "state-deal-kits",
    name: "State Deal Kits",
    phase: 3,
    status: "active",
    description: "State workflows, equipment, and documents",
  },
  {
    id: "compliance-engine",
    name: "Compliance Rules Engine",
    phase: 3,
    status: "active",
    description: "State compliance rules and workflow blockers",
  },
  {
    id: "lead-detail",
    name: "Lead Detail & CRM Pipeline",
    phase: 4,
    status: "active",
    description: "Lead intelligence and pipeline stages",
  },
  {
    id: "outreach-crm",
    name: "Outreach CRM",
    phase: 4,
    status: "active",
    description: "Respectful outreach templates and logs",
  },
  {
    id: "document-center",
    name: "Document Center",
    phase: 5,
    status: "active",
    description: "Templates, generators, and document workflow",
  },
  {
    id: "deal-calculator",
    name: "Deal Calculator",
    phase: 6,
    status: "active",
    description: "Estimated offer ranges and deal potential",
  },
  {
    id: "buyer-network",
    name: "Buyer Network",
    phase: 6,
    status: "active",
    description: "Buyer matching and disposition",
  },
  {
    id: "assignment-tracker",
    name: "Assignment Tracker",
    phase: 6,
    status: "active",
    description: "Assignment and closing workflow",
  },
  {
    id: "admin-console",
    name: "SCS Nova Admin Console",
    phase: 7,
    status: "active",
    description: "Platform administration and licensing",
  },
  {
    id: "audit-trail",
    name: "Audit Trail",
    phase: 7,
    status: "active",
    description: "Activity and compliance audit logging",
  },
  {
    id: "reports",
    name: "Reports",
    phase: 6,
    status: "active",
    description: "Pipeline and performance reporting",
  },
  {
    id: "launch-readiness",
    name: "Launch Readiness",
    phase: 8,
    status: "active",
    description: "Final integration, QA, security, and public launch pages",
  },
];
